#!/bin/bash
#SBATCH --chdir /home/ghio/covid/open-abm/
#SBATCH --job-name 200
#SBATCH --nodes 1
#SBATCH --tasks-per-node 1
#SBATCH --mem 124G
#SBATCH --time 2:00:00
#SBATCH -o output.out
#SBATCH -e error.out
#SBATCH --partition=serial
source .venvs/open-abm/bin/activate
module load gcc/8.4.0
module load python/3.7.7
module load gsl/2.5
module load py-pybind11/2.5.0
cd covid/open-abm/
python epi_delay.py 200


